// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// The agent figures as a plain-HTML snippet, for the template apps.
//
// Brief Maker and the Research Tool are plain HTML inside a .clan: no React,
// no bundler. They draw the same approved figures as the shell by inlining
// this snippet, which is AgentFigure rendered to static SVG once per agent,
// plus AgentFigure.css and a small `agentFigure(key, opts)` helper. The
// generated file is app/templates/shared/agent-figures.html (written by
// scripts/agent-figures.mjs; a test holds it to this function), and each
// template's packer (crates/clan-sdk/examples/make_*.rs) splices it in at the
// `<!-- @napkin:agent-figures -->` marker in the template's <head>.

import { renderToStaticMarkup } from 'react-dom/server'
import { AgentFigure } from './AgentFigure'
import { AGENTS, AGENT_KEYS } from './model'

export const FIGURES_MARKER = '<!-- @napkin:agent-figures -->'

/**
 * The helper the templates call. Plain ES5, no dependencies: it takes the
 * idle markup and sets the state, the stride, the label and the badge.
 *   agentFigure('drafter', {state:'working', label:'Drafter · Insight'})
 *   agentFigure('judge', {state:'needs-you'})
 *   agentFigure('extract', {decorative:true})
 */
const HELPER = `function agentFigure(key,o){
  var F=AGENT_FIGURES, s=F.svg[key]; if(!s) return ''; o=o||{};
  var st=o.state==='working'||o.state==='needs-you'?o.state:'idle';
  s=s.replace('data-state="idle"','data-state="'+st+'"'+(o.walking?' data-walking="true"':''));
  if(o.cls) s=s.replace('class="agent-figure"','class="agent-figure '+o.cls+'"');
  if(st==='needs-you') s=s.replace(/<\\/svg>$/,F.badge+'<\\/svg>');
  if(o.decorative) s=s.replace(/ role="img" aria-label="[^"]*"/,' aria-hidden="true" focusable="false"');
  else {
    var l=o.label||F.name[key]+', '+F.role[key];
    l+=st==='needs-you'?' \\u2014 needs you':st==='working'?' \\u2014 working':'';
    l=String(l).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});
    s=s.replace(/aria-label="[^"]*"/,'aria-label="'+l+'"');
  }
  return s;
}`

/** Escape for a JS string literal that sits inside an HTML <script>. */
function js(s: string): string {
  // JSON quoting, then keep the HTML parser from seeing a closing tag.
  return JSON.stringify(s).replace(/<\//g, '<\\/')
}

/** The whole snippet: the figure CSS, then the figures and the helper. */
export function figureSnippet(css: string): string {
  const svg: string[] = []
  const name: string[] = []
  const role: string[] = []
  let badge = ''
  for (const key of AGENT_KEYS) {
    svg.push(`${key}:${js(renderToStaticMarkup(<AgentFigure agent={key} />))}`)
    name.push(`${key}:${js(AGENTS[key].name)}`)
    role.push(`${key}:${js(AGENTS[key].role)}`)
    if (!badge) {
      const needs = renderToStaticMarkup(<AgentFigure agent={key} state="needs-you" />)
      badge = needs.slice(needs.indexOf('<g class="af-badge">'), needs.lastIndexOf('</svg>'))
    }
  }
  return [
    '<!-- Generated by app/scripts/agent-figures.mjs from app/src/studio/AgentFigure.tsx',
    '     and AgentFigure.css. Do not edit here: change the figures there and run',
    '     `npm run figures` in app/. -->',
    `<style id="agent-figures-css">\n${css.trim()}\n</style>`,
    '<script>',
    `var AGENT_FIGURES={svg:{${svg.join(',\n')}},\nname:{${name.join(',')}},\nrole:{${role.join(',')}},\nbadge:${js(badge)}};`,
    HELPER,
    '</script>',
    '',
  ].join('\n')
}
