//! What the template-app packers share: the agent figures every Napkin app
//! draws, and the app's mark.
//!
//! Included by `make_brief_maker.rs` and `make_campaign_research.rs` with
//! `#[path = "shared/app_ui.rs"] mod app_ui;` (cargo does not build this
//! directory as an example of its own).

use std::fs;
use std::path::Path;

/// Where a template's `<head>` asks for the figures.
pub const FIGURES_MARKER: &str = "<!-- @napkin:agent-figures -->";

/// Splice `app/templates/shared/agent-figures.html` — the shell's approved
/// agent figures as plain SVG, their CSS and the `agentFigure()` helper,
/// generated by `npm run figures` in app/ — into the template at its marker.
/// The snippet is checked for a closing `</body>`: the host injects its bridge
/// at the last one, and one inside a script would move it.
pub fn inline_figures(templates: &Path, html: &str) -> Result<String, Box<dyn std::error::Error>> {
    let snippet = fs::read_to_string(templates.join("shared/agent-figures.html")).map_err(|e| {
        format!("app/templates/shared/agent-figures.html: {e} (run `npm run figures` in app/)")
    })?;
    if snippet.to_ascii_lowercase().contains("</body") {
        return Err("the figure snippet contains </body>".into());
    }
    if html.matches(FIGURES_MARKER).count() != 1 {
        return Err(
            format!("the template needs exactly one {FIGURES_MARKER} in its <head>").into(),
        );
    }
    Ok(html.replacen(FIGURES_MARKER, snippet.trim_end(), 1))
}

/// Where an app's mark lives in its archive. The manifest's `app.icon` names
/// this member (spec §28: an archive path); the host hands it to the home
/// screen inline, as a `data:` URI, because a page cannot read into an archive.
pub const ICON_PATH: &str = "app/icon.svg";

/// The app's mark, `icon.svg` beside its index.html: a single shape on a
/// transparent ground. The home screen uses it as a mask and paints it in the
/// app's zone colours, so one mark reads in light and dark.
pub fn icon_svg(template: &Path) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let svg = fs::read(template.join("icon.svg"))?;
    if !String::from_utf8_lossy(&svg)
        .trim_start()
        .starts_with("<svg")
    {
        return Err("icon.svg must be a bare <svg> document".into());
    }
    Ok(svg)
}
